### ISSUE TITLE
Document CRON_SCHEDULE and tags

### ISSUE THREAD

**Issue by madalee-com** [fightforlife/docker_snapraid#3]
Hello,

I have a few documentation requests, if you have time to do some of them, that would be wonderful.  Thanks for this excellent image!

1. After you update any documentation on github, can you also update on dockerhub?  The most recent changes with the environment variable for CRON_SCHUDULE (great idea BTW) caused the containers to stop scheduling as the default for the EV is blank, meaning no cron would get scheduled.  And there wasn't anything on the dockerhub to explain this.

2. Can you set a default for the CRON_SCHEDULE EV?  As is, if the EV is not declared when running, nothing gets scheduled in cron, so the container breaks.

3. Can you please link back to your github from the dockerhub page?  That would have been really helpful when I was just trying to figure out why things weren't working.  I had to google search for your dockerhub image, which led to a single github memory page, which then led me to the github page.

4. Could you put a little more documentation about CRON_SCHEDULE? (I already figured it out by looking at the source, just wanting to help others).  

5. Could you document what each of your tags is?  I see *master*, which I assume means it pulls from the Snapraid master.  And then latest, 12.1, 11.6, and beta, I'm not sure what each pulls from.

Thanks again, whether or not you take care of any of these changes!

**Comment by fightforlife** [comment]
Hi @t3nk3y, I saw this way to late, I am sorry!

Thank you very much for your suggestions, here are some answers:

1. I removed the documentation on DockerHub and replaced it with a link to this Github Project. Then I do not need to maintain both.
2. I thought about setting a default value for CRON_SCHEDULE like every day at 3am. But this could cause someone to loose data when snapraid or the runner is not configured correctly.  At the moment I will leave this empty, so that the user has to set the CRON_SCHEDULE and therefor activate the snapraid routine manually.
3. done! (I really need to decide on an username.)
4. added a short explanation for the CRON_SCHEDULE and a link to https://crontab.guru/ to generate your own.
5. You are right, it is kind of a mess. You can find a short description of each release here: https://github.com/fightforlife/docker_snapraid/releases. Generally you should always use a specific version tag when you pull this image. This way you always get a variant of the image which will work with your config. (e.g. v11.6, v12.1, v12.1.1). I will never modify these images after they are published. 
New development takes place in 'latest/master'. These could also be breaking changes. so you should not reference these in the docker compose.
